language: cpp

sudo: false

matrix:
  include:
    - os: linux
      env:
        - system="x86_64"


before_install:
  - source .travis/setenv.sh

script: make

branches:
  only:
    - master

notifications:
  email: false
