language: cpp
sudo: false
dist: trusty
addons:
  apt:
    sources:
    - llvm-toolchain-trusty-4.0
    - sourceline: ppa:ricotz/toolchain
    packages:
    - clang-4.0
    - build-essential
    - ninja-build
matrix:
  include:
  - os: linux
    env:
    - system="x86_64"
before_script:
- mkdir -p $HOME/toolchain
- ln -s `which clang-4.0` $HOME/toolchain/gcc
- ln -s `which clang++-4.0` $HOME/toolchain/g++
- export PATH=$HOME/toolchain:$PATH
script: make
branches:
  only:
  - master
notifications:
  email: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: r7uZEwrKpxHemZuNdN/HfNTG4/fWbKTUEZ0fY63yhBPeiZ+Kyxdbx9HGNC9x/n/QsATQb65tSosu3WE7jBFPKf6tpK5/2CQ/J2G0Zok6N4pV3lG6v5WlfwJsbsWy7H63vL7S+bl/mmNOcJemmio0ZlzOyx1U1JnGYwOcRve4J6jYKdQJOUoskL+NnT2qPUpeaqR0iQ/INZsOJRhOEkDa6GWG1hINu+dEYpMNMjtc5jnr2yqRACpcqp/ufk8rAVc5gBtLk+EPTdmXQdKeoGyYMAf5OVXim8294edZMBoJAnVWIrYLJ7kYNtiwQYjPJxKm5HyIPLCH+eIHvIDOxXgXHZKJ3eiioW8RFkW2U8JDz3/GnzvTmofOsKnVvgVGbWNWLxLBg84QCdCOITR0aznkcjeoTToHLm3QPgbuVGx/OntAERSraP0VRimWHBXTO7jF7nT1QArB2dO7MEGbYexy3v6MznZeMxY6ul2VCakgwneCZpXUTVjPGxZ3+UFiv/ijAHY9m8N2ER1xvJX0h67a7HPzHuoLLwfC7nrvxc74OH0CgdxgGy3DmENGbiZtiTLeWaul+n1cU3hCPVIm/ySJskfv4nIaxFH4tGvD1D2JzFgOvlTjIkFdFWROmrsTXdqk3Fc9wku+ApaUPaGgTvt4s2qT9nBVzZJEe0e+zLMIGMM=
  file: out/Release/gn
  on:
    repo: twrl/generate-ninja
