language: cpp

sudo: false
dist: trusty 

addons:
  apt:
    sources:
    - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
    - gcc
    - g++
    - build-essential
    - ninja-build

matrix:
  include:
    - os: linux
      env:
        - system="x86_64"


#before_install:
#  - source .travis/setenv.sh

script: make

branches:
  only:
    - master

notifications:
  email: false
