language: cpp

sudo: false
dist: trusty 

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - build-essential
    - ninja-build

matrix:
  include:
    - os: linux
      env:
        - system="x86_64"
        - CC=gcc-4.9
        - CXX=g++-4.9


#before_install:
#  - source .travis/setenv.sh

script: env CC=gcc-5 CXX=g++-5 make

branches:
  only:
    - master

notifications:
  email: false
