language: cpp

sudo: false
dist: trusty 

addons:
  apt:
    sources:
    - llvm-toolchain-trusty-4.0
    - sourceline: "ppa:ricotz/toolchain"
    packages:
    - clang-4.0
    - build-essential
    - ninja-build

matrix:
  include:
    - os: linux
      env:
        - system="x86_64"


#before_install:
#  - source .travis/setenv.sh

before_script:
  - mkdir -p $HOME/toolchain
  - ln -s `which clang-4.0` $HOME/toolchain/gcc
  - ln -s `which clang++-4.0` $HOME/toolchain/g++
  - export PATH=$HOME/toolchain:$PATH
script: make

branches:
  only:
    - master

notifications:
  email: false
