language: cpp

sudo: false
dist: trusty 

addons:
  apt:
    sources:
    - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
    - gcc-6
    - g++-6
    - build-essential
    - ninja-build

matrix:
  include:
    - os: linux
      env:
        - system="x86_64"
        - CC=gcc-4.9
        - CXX=g++-4.9


#before_install:
#  - source .travis/setenv.sh

script: env CC=gcc-6 CXX=g++-6 make

branches:
  only:
    - master

notifications:
  email: false
